### ISSUE TITLE
GCC

### ISSUE THREAD

**Issue by Valby98** [HiPeRT/IndInf20#10]
Ragas sto avendo dei problemi con la compilazione di c++ mediante l'uso di dei comandi gcc (io uso Gitbash per scrivere i comandi invece di cygwin e come compilatore di c++ uso Dev-C++), in particolare mi evidenzia tutta una serie di riferimenti indefiniti. Qualcuno sa quale potrebbe essere il problema?

**Comment by pburgio** [comment]
Per piacere, posta l'errore e la riga di compilazione, così possiamo aiutarti meglio

**Comment by Valby98** [comment]
Questo è un esempio di quello che mi ha restituito (ho provato anche altri comandi)
 gcc blink.cpp blink1.cpp -Wall -o blink2.cpp
blink.cpp:2:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.
blink1.cpp:3:2: error: invalid preprocessing directive #ifnded
 #ifnded NO_PI
  ^~~~~~
blink1.cpp:4:22: fatal error: wiringPi.h: No such file or directory
 #include <wiringPi.h>
                      ^
compilation terminated.

**Comment by pburgio** [comment]
Beh è abbastanza semplice. wiringPi non esiste in un ambiente desktop, **come vi ho detto più volte oggi**.
La macro ```NO_PI``` e le corrispondenti ```#ifdef``` servono proprio ad evitare questi errori quando lavorate sul vostro computer (veda file blink.cpp), per poter sviluppare la parte algoritmica in tranquillità
