### ISSUE TITLE
Cambiare linguaggio di Codesys

### ISSUE THREAD

**Issue by pburgio** [HiPeRT/IndInf20#14]
Qualcuno scriva qui come si fa, grazie
(e usate sempre le issues)

**Comment by MatteoSpaggiari** [comment]
Per chi volesse cambiare lingua help.codesys.com/api-content/2/codesys/3.5.13.0/en/_cds_f_development_system_introduction/#:~:text=In%20the%20Option%20%E2%80%A3%20International,th….

Strumenti opzioni impostazioni internazionale
