### ISSUE TITLE
Libreria "CmpVisuHandler" mancante in CODESYS

### ISSUE THREAD

**Issue by Sladerix** [HiPeRT/IndInf20#16]
Seguendo le lezioni non mi trovavo perché non riuscivo a far funzionare la tab "Visualization".
L'ide mi lanciava un errore poiché non trovava la libreria.

Per risolvere ho fatto:
1. Doppio click su "Library Manager" dalla colonna di sinistra dell'ide (sotto "Application")
2. Cliccato su "Add Library" > "Advanced"
3. Cercato "CmpVisuHandler"
4. Doppio Click sul primo risultato (la libreria)

**Comment by pburgio** [comment]
Grazie
