### ISSUE TITLE
Moltitudine di errori dopo il "Build"

### ISSUE THREAD

**Issue by Sladerix** [HiPeRT/IndInf20#17]
Dopo aver provveduto a installare la libreria mancate, aver aggiungo la "Visualization1" come da esempio, e aver cliccato su "Build" per controllare che tutto fosse ok, l'IDE mi ha mostrato 500+ Errors. 
Tutti errori di compatibilità, conversioni non ammesse ecc...

Per risolvere ho fatto:
1. Tasto destro sul Device nella colonna di sinistra dell'IDE (sopra "PLC Logic")
2. "Update Device"
3. Spuntato la casella "Display all versions (for experts only)
4. Selezionato con doppio click il device "CODESYS Control WIN V3" Versione 3.5.10.30
5. Cliccato su "Close"

**Comment by pburgio** [comment]
Grazie
