### ISSUE TITLE
gihub

### ISSUE THREAD

**Issue by Valby98** [HiPeRT/IndInf20#2]
Ragas sto avendo dei problemi con github del tipo che quando cerco di clonare https:// github.com/...   oltre ad avvertirmi che clonando una directory vuota, non mi fa neanche aggiungere niente mi segnala accesso negato. Qualcuno saprebbe darmi una mano a risolvere il problema?

**Comment by Giada-Pezzali** [comment]
Sei loggato su GitHub mentre provi a clonarla? ( a me ha preso in automatico le credenziali, se no dovrebbe chiedertele in teoria )
Del resto dovrebbe bastare scrivere "git clone https://....." con il link che trovi nel pulsante verde con scritto "code"

**Comment by Valby98** [comment]
allora per quanto riguarda le credenziali me le ha chieste e ok ... poi però arrivo ad implementare il comando git push origin master e mi dà errore del tipo: 
error: failed to push some refs to 'https://github.com/Valby98/git.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by Valby98** [comment]
allora per quanto riguarda le credenziali me le ha chieste e ok... però quando implmento il comando git push origin master mi dà errore del tipo:
error: failed to push some refs to 'https://github.com/..........'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Integrate the remote changes (e.g.
hint: 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by Giada-Pezzali** [comment]
Credo ti dia errore perchè non siamo abilitati a utilizzare il comando push se stai lavorando con il master, quello possiamo solo aggiornarlo facendo pull.
Se invece stai usando il branch "students" non so se abbiamo l'abilitazione.

**Comment by Valby98** [comment]
infatti ho provato anche il comando pull restando master ma dà lo stesso errore

**Comment by TobiaPoppi** [comment]
Ciao @Valby98 
Prova ad andare nella cartella del repository che hai clonato localmente. 
Tasto destro dentro alla cartella e seleziona -> "Git Bash Here".
Dopodichè gli dai un "git pull".
Se ti da errore, fai copia e incolla qui che vediamo

**Comment by FabioMarinelli99** [comment]
io ho provato a pushare seguendo [queste istruzioni](https://devconnected.com/how-to-push-git-branch-to-remote/#:~:text=In%20order%20to%20push%20a,branch%20name%20to%20be%20pushed.&text=If%20you%20are%20not%20already,to%20switch%20to%20your%20branch.) ma il risultato è:
![Schermata da 2020-09-23 02-27-30](https://user-images.githubusercontent.com/71696117/93992550-fa503d00-fd8d-11ea-81ba-8e62898642b2.png)
help

**Comment by Valby98** [comment]
@TobiaPoppi credo di aver risolto il problema, alla fine quello che dovevo fare era fare un'operazione di merge per fare sì di unire le history. Grazie comunque e grazie anche a @Giada-Pezzali .

**Comment by pburgio** [comment]
Ciao a tutti, mi intrometto per dirvi che per pushare su "students", devo aggiungervi al gruppo "IndInf20", per darvi i diritti

(Se riuscite a pushare anche senza, allora c'è un problema di diritti d'accesso, e vi pregherei di segnalarmelo)
