### ISSUE TITLE
Non riesco a pushare

### ISSUE THREAD

**Issue by FabioMarinelli99** [HiPeRT/IndInf20#3]
ho seguito paro paro [queste indicazioni](https://opensource.com/article/19/7/create-pull-request-github) ma il risultato è
'remote: Permission to HiPeRT/IndInf20.git denied to FabioMarinelli99.
fatal: unable to access 'https://github.com/HiPeRT/IndInf20.git/': The requested URL returned error: 403'
![Schermata da 2020-09-23 12-01-15](https://user-images.githubusercontent.com/71696117/93999255-e1e42080-fd95-11ea-9623-f8b0e5c47d73.png)
help

**Comment by pburgio** [comment]
Salve, l'ho appena aggiunta al team "IndInf20", dovrebbe essere in grado di pushare

Mi faccia sapere

**Comment by FabioMarinelli99** [comment]
Confermo, sono riuscito a fare la push.
Ad ogni modo al posto di pushare un nuovo branch ho creato una cartella 'fabio_marinelli' nel branch students nella cartella Code, perché se ognuno facesse un proprio branch poi students diventerebbe inutile, giusto...?

**Comment by pburgio** [comment]
...sì, l'idea sarebbe quella. In realtà, per come andrebbero fatte le cose, io dovrei "bloccare" il branch studenti, e costringervi a crearne uno vostro a partire da quello

**Comment by johanz9** [comment]
Salve, anch'io ho lo stesso problema, mi da: "fatal: unable to access....."

**Comment by pburgio** [comment]
Esatto, dovrò dare i diritti al suo utente. Vi pregherei di sentire tutti i vostri colleghi e di raccogliere gli utenti vari di chi è interessato ad accedere in scrittura, così che io possa inserirvi una sola volta
