### ISSUE TITLE
Permesso di fare Merge in Students

### ISSUE THREAD

**Issue by tobi1modna** [HiPeRT/IndInf20#9]
@pburgio Come da lei proposto insieme a @FabioMarinelli99 ho creato il branch "students_patchMarinelliPoppi" a partire da students.
Ho spostato i suoi due file e i nostri due file all'interno di una nuova cartella "Automata-1", dopodichè ho inviato la pull request dal nuovo branch, verso "students".
In seguito mi ha fatto fare il Merge senza nessun problema.
Quindi se lei non vuole farci avere il permesso di poter fare Merge, non sta funzionando

**Comment by pburgio** [comment]
Ciao, no, parlavo proprio su master (che fra l'altro ho modificato...)
